### ISSUE TITLE
Roborock S5/S5Max - Dust container is full, please empty

### ISSUE THREAD

**Issue by Loxfreek** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#37]
Is it possible to include this message in your protocol? 
Original App is pushing this messages regularly.

**Comment by mschlenstedt** [comment]
We already had this discussion in Loxforum. I could remember that this isn't possible because its some kind of a push message but not a regular state/error_code. But you can check:

If this is a seperate state/error_code of the robot, I can include it. Check the Status Button in the plugin and figure out the state or error_code it prints out when the dust bin is full.

```
/usr/local/bin/miiocli  -o json_pretty roborockvacuum --ip 192.168.3.40 --token 776b50xxxxxxxxxxb494f31786456 status  2>&1

Output:

{
  "msg_ver": 8,
  "msg_seq": 265,
  "state": 8,
  "battery": 100,
  "clean_time": 2814,
  "clean_area": 44287500,
  "error_code": 0,
  "map_present": 1,
  "in_cleaning": 0,
  "fan_power": 90,
  "dnd_enabled": 1
}
```

Currently known codes are in our wiki (see tables below): https://loxwiki.atlassian.net/wiki/spaces/LOXBERRY/pages/1219756048/MiRobot2Lox-NG#MiRobot2Lox-NG-Codes

**Comment by Loxfreek** [comment]
> We already had this discussion in Loxforum. I could remember that this isn't possible because its some kind of a push message but not a regular state/error_code. But you can check:
> 
> If this is a seperate state/error_code of the robot, I can include it. Check the Status Button in the plugin and figure out the state or error_code it prints out when the dust bin is full.
> 
> ```
> /usr/local/bin/miiocli  -o json_pretty roborockvacuum --ip 192.168.3.40 --token 776b50xxxxxxxxxxb494f31786456 status  2>&1
> 
> Output:
> 
> {
>   "msg_ver": 8,
>   "msg_seq": 265,
>   "state": 8,
>   "battery": 100,
>   "clean_time": 2814,
>   "clean_area": 44287500,
>   "error_code": 0,
>   "map_present": 1,
>   "in_cleaning": 0,
>   "fan_power": 90,
>   "dnd_enabled": 1
> }
> ```
> 
> Currently known codes are in our wiki (see tables below): https://loxwiki.atlassian.net/wiki/spaces/LOXBERRY/pages/1219756048/MiRobot2Lox-NG#MiRobot2Lox-NG-Codes

Thanks
I will check next time and give feedback
